
server:
  port: 8086

spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 10
      properties:
             enable.idempotence: true
             retry.backoff.ms: 1000
             max.in.flight.requests.per.connection: 5
             delivery.timeout.ms: 120000
             request.timeout.ms: 120000
             linger.ms : 0






































